name: ci
on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  caller:
     uses: wechorg/templateworkflows/.github/workflows/main.yml@main
   
